### ISSUE TITLE
Binding image (wind_data.png) to texture 

### ISSUE THREAD

**Issue by ebefarooqui** [weatherlayers/deck.gl-particle#6]
Could someone describe how it is the image is written into a texture such that web gl can read from it in the transform shader? 

Currently, it appears that the image isn't asynchronously loaded from the asset url but rather that the image url is passed as a uniform into the shader. Where is the image texture created and bound?

(Just wanted some explanation here! Very helpful project :))

**Comment by zakjan** [comment]
Hi, the URL is loaded and the texture is created asynchronously by deck.gl, see docs https://deck.gl/docs/developer-guide/custom-layers/prop-types

> async (boolean, optional) - if true, the prop can either be a [Promise](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves to its actual value, or an url string (loaded using the base Layer's [fetch](https://deck.gl/docs/api-reference/core/layer) prop).

**Comment by zakjan** [comment]
Here it is in the code https://github.com/visgl/deck.gl/blob/c831ae1ea997c054c5a4a3962ee94f4ee9c999a3/modules/core/src/lifecycle/component-state.ts#L150
